astra_db:
  collection_name: "customer_review_collection"

pinecone_db:
  index_name: "customer-review-index"

retriever:
  top_k: 3
  score_threshold: 0.5

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  provider: "google"
  model_name: "deepseek-r1-distill-llama-70b" 