astra_db:
  collection_name: "customer_review_collection"

pinecone_db:
  index_name: "customer-review-index"

retriever:
  top_k: 10
  score_threshold: 0.5

embedding_model:
  default_provider: "google"
  providers:
    google:
      model_name: "models/text-embedding-004"

llm:
  default_provider: "google"  # change to "groq" if needed
  providers:
    google:
      model_name: "gemini-2.0-flash-lite"
    groq:
      model_name: "deepseek-r1-distill-llama-70b"

safeguard:
    groq:
      model_name: "meta-llama/llama-guard-4-12b"